name: Build Kernel

on:
  workflow_call:
    inputs:
      include_ksu:
        required: false
        type: string
      kernel_git:
        required: false
        type: string
      kernel_branch:
        required: false
        type: string
      device_defconfig:
        required: false
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build-kernel:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        id: build
        run: |
            echo "Building ${{ inputs.include_ksu }}"
            sudo bash main.sh ${{ inputs.include_ksu }} ${{ inputs.kernel_git }} ${{ inputs.kernel_branch }} ${{ inputs.device_defconfig }}
      - name: Prepare Upload
        id: prepare
        run: |
          cd $GITHUB_WORKSPACE/out
          zip_name="$(ls *.zip)"
          echo "kernel_name=${zip_name::-4}" >> $GITHUB_ENV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.kernel_name }}
          path: out/*
